<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KhachHangSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('khach_hangs')->delete();
        DB::table('khach_hangs')->truncate();
        DB::table('khach_hangs')->insert([

            [
                'ma_kh' => 'KH01',
                'mat_khau' => '123456',
                'ho_ten' => 'Nguyễn Thị G',
                'email' => 'nguyenthig@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0900111222',
                'created_at' => '2025-06-02 00:00:00',
                'avatar' => 'https://png.pngtree.com/png-vector/20201223/ourlarge/pngtree-cute-cartoon-hand-drawn-cow-animal-avatar-vector-png-image_2591528.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH02',
                'mat_khau' => '123456',
                'ho_ten' => 'Trần Văn H',
                'email' => 'tranvanh@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0911002200',
                'created_at' => '2025-06-02 00:00:00',
                'avatar' => 'https://if24h.com/wp-content/uploads/2024/10/avatar-cute-hai.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH03',
                'mat_khau' => '123456',
                'ho_ten' => 'Lê Thị I',
                'email' => 'lethii@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0922334455',
                'created_at' => '2025-06-02 00:00:00',
                'avatar' => 'https://if24h.com/wp-content/uploads/2024/10/avatar-vo-tri-thu-vi.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH04',
                'mat_khau' => '123456',
                'ho_ten' => 'Phạm Văn J',
                'email' => 'phamvanj@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0933445566',
                'created_at' => '2025-06-12 00:00:00',
                'avatar' => 'https://if24h.com/wp-content/uploads/2024/10/hinh-vo-tri-tai-nang.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH05',
                'mat_khau' => '123456',
                'ho_ten' => 'Nguyễn Thị K',
                'email' => 'nguyenthik@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0944556677',
                'created_at' => '2025-06-13 00:00:00',
                'avatar' => 'https://tamkytourism.com/wp-content/uploads/2025/02/avatar-vo-tri-9.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH06',
                'mat_khau' => '123456',
                'ho_ten' => 'Trần Văn L',
                'email' => 'tranvanl@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0955667788',
                'created_at' => '2025-06-16 00:00:00',
                'avatar' => 'https://jbagy.me/wp-content/uploads/2025/03/hinh-anh-cute-avatar-vo-tri-3.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH07',
                'mat_khau' => '123456',
                'ho_ten' => 'Lê Thị M',
                'email' => 'lethim@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0966778899',
                'created_at' => '2025-06-23 00:00:00',
                'avatar' => 'https://tamkytourism.com/wp-content/uploads/2025/02/avatar-vo-tri-17.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH08',
                'mat_khau' => '123456',
                'ho_ten' => 'Phạm Văn N',
                'email' => 'phamvann@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0977889900',
                'created_at' => '2025-06-23 00:00:00',
                'avatar' => 'https://avatarvotri.com/wp-content/uploads/2025/04/hinh-avatar-vo-tri-cute.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH09',
                'mat_khau' => '123456',
                'ho_ten' => 'Nguyễn Thị O',
                'email' => 'nguyenthio@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0988990011',
                'created_at' => '2025-06-23 00:00:00',
                'avatar' => 'https://m.yodycdn.com/products/anhvotricuteyodyvn25_m3qzikx6b30e6y10cbt.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH10',
                'mat_khau' => '123456',
                'ho_ten' => 'Trần Văn P',
                'email' => 'tranvanp@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0999001122',
                'created_at' => '2025-06-30 00:00:00',
                'avatar' => 'https://avatarvotri.com/wp-content/uploads/2025/04/avatar-vo-tri-dep-ngau.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH11',
                'mat_khau' => '123456',
                'ho_ten' => 'Nguyễn Thị Q',
                'email' => 'nguyenthiq@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0902233445',
                'created_at' => '2025-06-23 00:00:00',
                'avatar' => 'https://aic.com.vn/wp-content/uploads/2024/10/avatar-vo-tri-meo-99mOYjIu.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH12',
                'mat_khau' => '123456',
                'ho_ten' => 'Trần Văn R',
                'email' => 'tranvanr@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0912333444',
                'created_at' => '2025-06-29 00:00:00',
                'avatar' => 'https://cdn2.fptshop.com.vn/unsafe/1920x0/filters:format(webp):quality(75)/avatar_vo_tri_a49436c5de.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH16',
                'mat_khau' => '123456',
                'ho_ten' => 'Phạm Thị Dung',
                'email' => 'dungpham@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0934567890',
                'created_at' => '2025-07-01 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbs2v0uFR7wdi4pE7aPfJVWYqTYA6TCsjGzw&s',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH17',
                'mat_khau' => '123456',
                'ho_ten' => 'Nguyễn Văn A',
                'email' => 'nguyenvana@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0912345678',
                'created_at' => '2025-07-01 00:00:00',
                'avatar' => 'https://vnclass.edu.vn/wp-content/uploads/2025/02/avatar-vo-tri-26.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH18',
                'mat_khau' => '123456',
                'ho_ten' => 'Trần Thị B',
                'email' => 'tranthib@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0945678901',
                'created_at' => '2025-06-12 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqHjzlT06c9-tkO9H8bQhNzDu67GadK6o21Q&s',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH19',
                'mat_khau' => '123456',
                'ho_ten' => 'Lê Văn C',
                'email' => 'levanc@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0912345678',
                'created_at' => '2025-06-12 00:00:00',
                'avatar' => 'https://jbagy.me/wp-content/uploads/2025/03/Hinh-anh-avatar-chibi-gau-truc-2.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH20',
                'mat_khau' => '123456',
                'ho_ten' => 'Nguyễn Thị D',
                'email' => 'nguyenthid@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0987654321',
                'created_at' => '2025-06-12 00:00:00',
                'avatar' => 'https://img.tripi.vn/cdn-cgi/image/width=700,height=700/https://gcs.tripi.vn/public-tripi/tripi-feed/img/474082XUL/avatar-bua-hai-huoc-va-bua-nhat_044337182.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH21',
                'mat_khau' => '123456',
                'ho_ten' => 'Trần Minh E',
                'email' => 'tranminhe@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0901234567',
                'created_at' => '2025-07-01 00:00:00',
                'avatar' => 'https://live.staticflickr.com/4029/35667852906_6ffb006961_m.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH22',
                'mat_khau' => '123456',
                'ho_ten' => 'Phạm Quỳnh F',
                'email' => 'phamquynhf@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0934567890',
                'created_at' => '2025-06-29 00:00:00',
                'avatar' => 'https://tophinhanh.net/wp-content/uploads/2024/01/avatar-maruko-cute-2.jpg',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH23',
                'mat_khau' => '123456',
                'ho_ten' => 'Trần Văn V',
                'email' => 'tranvanv@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0908777666',
                'created_at' => '2025-06-12 00:00:00',
                'avatar' => 'https://png.pngtree.com/png-vector/20191027/ourmid/pngtree-cute-wolf-avatar-with-a-yellow-background-png-image_1873506.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH24',
                'mat_khau' => '123456',
                'ho_ten' => 'Nguyễn Thị W',
                'email' => 'nguyenthiw@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0919888777',
                'created_at' => '2025-06-12 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpZY_s2J1wf1jFko6cvIZAqsjuIGfTQdfJjA&s',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH25',
                'mat_khau' => '123456',
                'ho_ten' => 'Lê Văn X',
                'email' => 'levanx@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0929777666',
                'created_at' => '2025-06-12 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSbVHETUO1t6v_nb-7fuMTbHAVOP1zf6koLg&s',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH26',
                'mat_khau' => '123456',
                'ho_ten' => 'Phạm Thị Y',
                'email' => 'phamthiy@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0939666555',
                'created_at' => '2025-06-13 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_rS-7D2y1Rh8njxtReQ4g3Afao8iEr6SHlA&s',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH27',
                'mat_khau' => '123456',
                'ho_ten' => 'Ngô Văn Z',
                'email' => 'ngovanz@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0949555444',
                'created_at' => '2025-06-13 00:00:00',
                'avatar' => 'https://m.yodycdn.com/products/anhvotricuteyodyvn5_m3qzhq75c9l8j2ymfo.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH28',
                'mat_khau' => '123456',
                'ho_ten' => 'Hoàng Thị AA',
                'email' => 'hoangthiaa@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0959444333',
                'created_at' => '2025-06-13 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTApBTQNOxendzx-mpRwwwJUMuFw09DiZt7ug&s',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH29',
                'mat_khau' => '123456',
                'ho_ten' => 'Đặng Văn BB',
                'email' => 'dangvanbb@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0969333222',
                'created_at' => '2025-06-16 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA5W8mmdqgticBgvZuCKQ30R7Tez2grRh9fA&s',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH30',
                'mat_khau' => '123456',
                'ho_ten' => 'Phan Thị CC',
                'email' => 'phanthicc@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0979222111',
                'created_at' => '2025-06-16 00:00:00',
                'avatar' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE84ZkAzHiXWkFTmCj7wCW2wmoSVweoOG95A&s',
                'gioi_tinh' => 0,
            ],
            [
                'ma_kh' => 'KH31',
                'mat_khau' => '123456',
                'ho_ten' => 'Lý Văn DD',
                'email' => 'lyvandd@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0989111000',
                'created_at' => '2025-06-16 00:00:00',
                'avatar' => 'https://vnclass.edu.vn/wp-content/uploads/2025/02/avatar-vo-tri-2.jpg',
                'gioi_tinh' => 1,
            ],
            [
                'ma_kh' => 'KH32',
                'mat_khau' => '123456',
                'ho_ten' => 'Tạ Thị EE',
                'email' => 'tathiee@gmail.com',
                'dia_chi' => '456 Le Loi, Ho Chi Minh City',
                'sdt' => '0999000111',
                'created_at' => '2025-06-16 00:00:00',
                'avatar' => 'https://i.pinimg.com/736x/56/72/d6/5672d634f75f75edb6e8cd3de03f099e.jpg',
                'gioi_tinh' => 0,
            ],


        ]);
    }
}
